const $=s=>document.querySelector(s),V=id=>($('#'+id)||{}).value||'',K='unsung_';
const ld=k=>{try{return JSON.parse(localStorage.getItem(K+k))}catch(e){return null}},sv=(k,v)=>{try{localStorage.setItem(K+k,JSON.stringify(v))}catch(e){}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const MN='January February March April May June July August September October November December'.split(' ');
const FEST={'2026-01-01':'New Year','2026-01-26':'Republic Day','2026-03-04':'Holi','2026-08-15':'Independence Day','2026-09-14':'Ganesh Chaturthi','2026-10-02':'Gandhi Jayanti','2026-10-20':'Dussehra','2026-11-08':'Diwali','2026-12-25':'Christmas'};
let U,D,mode='in',tb=0,cm=new Date().getFullYear()==2026?new Date().getMonth():0,sd='',fired={},rec=null,mt=null,ms=0,cb=[],tb2=[],noteEditor=false;
const save=()=>sv('d_'+U,D),show=id=>{document.querySelectorAll('.scr').forEach(s=>s.classList.toggle('on',s.id==id));scrollTo(0,0)};
const yt=q=>'https://www.youtube.com/results?search_query='+encodeURIComponent(q),gg=q=>'https://www.google.com/search?q='+encodeURIComponent(q);
function theme(){const r=document.documentElement,d=r.dataset.theme=='dark'||(!r.dataset.theme&&matchMedia('(prefers-color-scheme:dark)').matches);r.dataset.theme=d?'light':'dark'}
async function hs(s){try{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch(e){return btoa(s)}}
function setMode(m){mode=m;$('#ab').textContent=m=='in'?'Log in':'Create account & save password'}
async function auth(){const e=V('em').trim().toLowerCase(),p=V('pw'),m=$('#ms');if(!e||p.length<4){m.textContent='Enter email and a password of 4+ characters';return}
const us=ld('users')||{},h=await hs(p);
if(mode=='up'){if(us[e]){m.textContent='Account exists – please log in';return}us[e]=h;sv('users',us)}else if(us[e]!==h){m.textContent='Wrong email or password (or sign up first)';return}
U=e;D=ld('d_'+e)||{alarms:[],ev:{},bills:[],kids:[],appts:[],tasks:[],movies:[],log:{},vet:[],baby:{},pet:{}};$('#mail')&&($('#mail').value=e);save();D.p?splash():show('prof')}
function saveP(){if(!V('n').trim()){alert('Please enter your name');return}
D.p={};['n','mail','mob','baby','kids','pet','old','work','co','back','out','ecn','ecp','city'].forEach(k=>D.p[k]=V(k));save();splash()}
function splash(){show('splash');setTimeout(()=>{if($('#splash').classList.contains('on'))home()},4000)}
function logout(){U=null;stopV();show('login')}
function home(){show('app');$('#hi').textContent='Hi '+D.p.n+' 👋';$('#sb').textContent='🚨 SOS – call '+(D.p.ecn||'contact');dashboard()}
function dashboard(){$('#launcher').hidden=false;$('#moduleView').hidden=true;$('#workTile').hidden=!D.p||D.p.work!='yes';notes()}
function tab(i){tb=i;$('#launcher').hidden=true;$('#moduleView').hidden=false;$('#moduleTitle').textContent=['Household','Care giving','Self care','Statistics','Work'][i];rr()}
function rr(){$('#mn').innerHTML=[r0,r1,r2,r3,r4][tb]();notes()}
function notes(){D.notes=D.notes||[];const n=[],p=D.p,now=new Date(),td=iso(now),tm=new Date(td);
D.alarms.forEach(a=>n.push('⏰ '+a.t+' '+a.l));(D.ev[td]||[]).forEach(e=>n.push('📅 Today: '+e));if(FEST[td])n.push('🎉 '+FEST[td]);
D.bills.forEach(b=>{const d=Math.round((new Date(b.d)-tm)/864e5);if(d<=3)n.push('💳 '+b.n+' ₹'+b.a+(d<0?' overdue':d==0?' due today':' due in '+d+'d'))});
D.appts.forEach(a=>{const d=Math.round((new Date(a.d.slice(0,10))-tm)/864e5);if(d>=0&&d<=1)n.push('🩺 '+a.t+' '+(d?'tomorrow ':'today ')+a.d.slice(11))});
D.vet.forEach(a=>{if(a.d==td)n.push('🐾 Vet visit today: '+a.t)});
const b=D.baby;if(+p.baby>0){if(b.sleep)n.push('👶 Sleep '+b.sleep+' · Wake '+(b.wake||'-'));if(b.food)n.push('🍼 Baby food '+b.food);if(b.med)n.push('💊 Baby medicine '+b.med+' '+(b.mn||''))}
if(+p.pet>0&&D.pet.food)n.push('🐶 Pet food '+D.pet.food+' · walk '+(D.pet.walk||'-'));
if(p.work=='yes')n.push('🏢 Leave work '+(D.workOut||p.out));
D.tasks.filter(t=>!t.x).slice(0,2).forEach(t=>n.push('📝 '+t.t));
const cl=['#fff3a8','#ffd1e3','#c9f0dd','#d6dcff','#ffe0b8'];
$('#nt').innerHTML=`${noteEditor?'<form class="note-compose" onsubmit="saveNote(event)"><textarea id="noteDraft" placeholder="Write a note…" aria-label="Sticky note text" required></textarea><div class="note-compose-actions"><button type="button" class="g" onclick="closeNoteEditor()">Cancel</button><button type="submit">Save</button></div></form>':'<button class="note-add" type="button" onclick="createNote()" aria-label="Create sticky note" title="Create sticky note">+</button>'}${D.notes.map((t,i)=>`<div class="note note-user" style="background:${cl[i%cl.length]};--r:${(i%2?1:-1)*(1+i%3)}deg"><button class="note-delete" type="button" onclick="removeNote(${i})" aria-label="Delete sticky note" title="Delete note">×</button><span>${esc(t)}</span></div>`).join('')}${n.map((t,i)=>`<div class="note" style="background:${cl[(i+D.notes.length)%cl.length]};--r:${(i%2?1:-1)*(1+i%3)}deg">${t}</div>`).join('')}`}
function createNote(){noteEditor=true;notes();$('#noteDraft').focus()}
function saveNote(e){e.preventDefault();const text=V('noteDraft').trim();if(!text)return;D.notes=D.notes||[];D.notes.unshift(text);noteEditor=false;save();notes()}
function closeNoteEditor(){noteEditor=false;notes()}
function removeNote(i){D.notes.splice(i,1);save();notes()}
function toast(t){const e=$('#ts');e.textContent=t;e.style.display='block';beep();setTimeout(()=>e.style.display='none',6000)}
function beep(){try{const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator();o.frequency.value=880;o.connect(a.destination);o.start();setTimeout(()=>o.stop(),700)}catch(e){}}
setInterval(()=>{if(!D||!U)return;const n=new Date(),hm=n.toTimeString().slice(0,5),k=iso(n)+hm;
const f=(id,m)=>{if(!fired[id+k]){fired[id+k]=1;toast(m)}};
D.alarms.forEach(a=>{if(a.t==hm)f('a'+a.t,'⏰ '+a.l)});
if(D.p&&D.p.work=='yes'){const [h,m]=(D.workOut||D.p.out||'18:00').split(':').map(Number),d=new Date(n);d.setHours(h,m-(Number(D.workLead)||15),0,0);if(d.toTimeString().slice(0,5)==hm)f('o'+(D.workLead||15),'🚕 Time to wrap up – book your cab now (Work tab)')}
if(D.baby&&(D.baby.food==hm||D.baby.med==hm))f('b','👶 Baby '+(D.baby.med==hm?'medicine':'food')+' time')},15000);
function add(key,o,first){if(!o[first])return;D[key].push(o);save();rr()}
function del(k,i){D[k].splice(i,1);save();rr()}
function list(k,fn){return D[k].map((x,i)=>`<div class="li"><span>${fn(x,i)}</span><button class="x" onclick="del('${k}',${i})">✕</button></div>`).join('')||'<small>Nothing yet</small>'}
/* Household */
function r0(){const p=D.p,td=iso(new Date());
return `<div class="c"><h3>⏰ Morning alarm</h3><div class="row"><input type="time" id="at" value="06:30"><input id="al" placeholder="Label" value="Good morning!"><button onclick="add('alarms',{t:V('at'),l:V('al')},'t')">Add</button></div>${list('alarms',a=>a.t+' – '+a.l)}<small>Keep this tab open for the alarm to ring.</small></div>
<div class="c"><h3>📅 Calendar 2026</h3>${calH()}</div>
<div class="c"><h3>🍳 Recipe helper</h3><div class="chat" id="ch">${chatH(cb)}</div><div class="row"><input id="ci" placeholder="e.g. paneer, dal, pasta…" style="flex:1" onkeydown="if(event.key=='Enter')recipe()"><button onclick="recipe()">Ask</button></div></div>
${+p.baby>0?`<div class="c"><h3>👶 Baby routine</h3><div class="f"><label>Sleep time</label><input type="time" id="bs" value="${D.baby.sleep||''}"><label>Wake time</label><input type="time" id="bw" value="${D.baby.wake||''}"><label>Feeding time</label><input type="time" id="bf" value="${D.baby.food||''}"><label>Medicine time & name</label><input type="time" id="bm" value="${D.baby.med||''}"><input id="bn" placeholder="Medicine name" value="${D.baby.mn||''}"><button onclick="D.baby={sleep:V('bs'),wake:V('bw'),food:V('bf'),med:V('bm'),mn:V('bn')};save();rr();toast('Saved')">Save</button></div></div>`:''}
${+p.pet>0?`<div class="c"><h3>🐶 Pet care</h3><div class="f"><label>Food time</label><input type="time" id="pf" value="${D.pet.food||''}"><label>Walking time</label><input type="time" id="pw2" value="${D.pet.walk||''}"><button onclick="D.pet={food:V('pf'),walk:V('pw2')};save();rr();toast('Saved')">Save</button></div><b>Vet appointments</b><div class="row"><input type="date" id="vd"><input id="vt" placeholder="Reason"><button onclick="add('vet',{d:V('vd'),t:V('vt')||'Vet'},'d')">Add</button></div>${list('vet',v=>v.d+' – '+v.t)}</div>`:''}
<div class="c"><h3>⏱ Time counter</h3>${trkH()}</div>
<div class="c"><h3>💳 Bills & recharges</h3><div class="row"><input id="bnm" placeholder="Bill / recharge"><input id="bam" type="number" placeholder="₹" style="width:90px"><input id="bd" type="date"><button onclick="add('bills',{n:V('bnm'),a:V('bam'),d:V('bd')},'d')">Add</button></div>${list('bills',b=>b.n+' ₹'+b.a+' · due '+b.d)}</div>`}
function calH(){const f=new Date(2026,cm,1).getDay(),n=new Date(2026,cm+1,0).getDate();let g=['S','M','T','W','T','F','S'].map(x=>`<b>${x}</b>`).join('')+'<i></i>'.repeat(f);
for(let d=1;d<=n;d++){const k=iso(new Date(2026,cm,d));g+=`<u class="${(D.ev[k]||[]).length||FEST[k]?'m':''} ${k==sd?'s':''}" onclick="sd='${k}';rr()">${d}</u>`}
let x='';if(sd)x=`<div><b>${sd}</b> ${FEST[sd]?'🎉 '+FEST[sd]:''}${(D.ev[sd]||[]).map((e,i)=>`<div class="li">${e}<button class="x" onclick="D.ev['${sd}'].splice(${i},1);save();rr()">✕</button></div>`).join('')}<div class="row"><input id="ev" placeholder="Mark event / birthday…" style="flex:1"><button onclick="if(V('ev')){(D.ev[sd]=D.ev[sd]||[]).push(V('ev'));save();rr()}">Mark</button></div></div>`;
return `<div class="row"><button onclick="cm=(cm+11)%12;rr()">‹</button><b>${MN[cm]} 2026</b><button onclick="cm=(cm+1)%12;rr()">›</button></div><div class="cal">${g}</div>${x}<small>Festival dates are indicative – verify locally.</small>`}
const chatH=a=>a.map(m=>`<p class="${m[0]?'me':''}">${m[1]}</p>`).join('');
const RC={paneer:'Paneer butter masala: sauté onion-tomato-cashew paste in butter, add kasuri methi, cream, garam masala, then paneer cubes; simmer 5 min.',dal:'Dal tadka: pressure-cook toor dal with turmeric (3 whistles). Temper ghee, cumin, garlic, chilli, tomato; mix and simmer 5 min.',khichdi:'Khichdi: rinse rice + moong dal 1:1, cook with turmeric, salt, 4 parts water till mushy; top with ghee.',poha:'Poha: rinse flattened rice, temper mustard, curry leaves, peanuts, onion, turmeric; add poha, salt, lemon.',pasta:'Pasta: boil till al dente; sauté garlic, tomato puree, herbs, veggies; toss with pasta and cheese.',omelette:'Omelette: beat 2 eggs, salt, onion, chilli, coriander; cook on buttered pan 2 min per side.',chai:'Masala chai: boil water with ginger, cardamom; add tea, milk, sugar; simmer 3 min and strain.',roti:'Roti: knead atta with water and salt into soft dough; rest 15 min; roll and cook on hot tawa.',upma:'Upma: roast rava; temper mustard, curry leaves, onion, chilli; add 2 parts water, salt; stir in rava.',rice:'Rice: rinse, 1 part rice to 2 parts water, cook covered 12–15 min on low; rest 5 min.'};
function recipe(){const q=V('ci').trim().toLowerCase();if(!q)return;cb.push([1,q]);const k=Object.keys(RC).find(x=>q.includes(x));cb.push([0,k?RC[k]:`I don't have that saved. <a href="${yt(q+' recipe')}" target="_blank">Watch recipes</a> · <a href="${gg(q+' recipe')}" target="_blank">Read recipes</a>`]);rr()}
const CATS=['Cooking','Cleaning','Laundry','Child/elder care','Shopping','Other'];
function trkH(){const td=iso(new Date());D.log[td]=D.log[td]||{};let tot=0,rows='';CATS.forEach(c=>{const m=Math.round((D.log[td][c]||0)+(D.run&&D.run.c==c?(Date.now()-D.run.s)/6e4:0));tot+=m;rows+=`<div class="li"><span>${c}: ${m} min</span><button class="${D.run&&D.run.c==c?'x':'g'}" onclick="trk('${c}')">${D.run&&D.run.c==c?'Stop':'Start'}</button></div>`});
return rows+`<div class="big">${(tot/60).toFixed(1)} h</div><p style="text-align:center">Household work today · Free time (of 16 waking h): <b>${Math.max(0,16-tot/60).toFixed(1)} h</b></p>`}
function trk(c){const td=iso(new Date());if(D.run){const m=(Date.now()-D.run.s)/6e4;D.log[td][D.run.c]=(D.log[td][D.run.c]||0)+m;const same=D.run.c==c;D.run=null;if(same){save();rr();return}}D.run={c,s:Date.now()};save();rr()}
const CHART_COLORS=['#d75b70','#347f68','#4f70bd','#bd762f','#8958a6','#333d4a'];
function r3(){const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-6+i);return d}),keys=days.map(iso),data=CATS.map(c=>keys.map(k=>(D.log[k]&&D.log[k][c]||0))),today=iso(new Date());
if(D.run&&keys.includes(today)){const ci=CATS.indexOf(D.run.c),di=keys.indexOf(today);if(ci>=0)data[ci][di]+=(Date.now()-D.run.s)/6e4}
const max=Math.max(60,...data.flat()),step=Math.ceil(max/4/30)*30,top=step*4,left=48,right=12,chartW=640-left-right,chartH=250-24-34,x=i=>left+i*chartW/6,y=v=>250-34-v/top*chartH;
const grid=Array.from({length:5},(_,i)=>{const v=i*step,yy=y(v);return `<line x1="${left}" y1="${yy}" x2="${640-right}" y2="${yy}" class="chart-grid"/><text x="${left-8}" y="${yy+4}" text-anchor="end" class="chart-label">${v}m</text>`}).join('');
const lines=data.map((values,i)=>`<polyline points="${values.map((v,j)=>`${x(j)},${y(v)}`).join(' ')}" fill="none" stroke="${CHART_COLORS[i]}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${values.map((v,j)=>`<circle cx="${x(j)}" cy="${y(v)}" r="4" fill="${CHART_COLORS[i]}"><title>${CATS[i]}: ${Math.round(v)} min on ${keys[j]}</title></circle>`).join('')}`).join('');
const labels=days.map((d,i)=>`<text x="${x(i)}" y="238" text-anchor="middle" class="chart-label">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d.getDay()]} ${d.getDate()}</text>`).join('');
const legend=CATS.map((c,i)=>`<span class="chart-legend-item"><i style="background:${CHART_COLORS[i]}"></i>${c}</span>`).join('');
const totals=data.map((values,i)=>({name:CATS[i],minutes:values.reduce((a,b)=>a+b,0),color:CHART_COLORS[i]})).sort((a,b)=>b.minutes-a.minutes),total=totals.reduce((a,v)=>a+v.minutes,0);
return `<div class="c"><h3>📈 Household work · last 7 days</h3><p>${Math.round(total)} min tracked across all work</p><svg class="work-chart" viewBox="0 0 640 250" role="img" aria-label="Line chart showing minutes spent on each household work category over the last seven days">${grid}${lines}${labels}</svg><div class="chart-legend">${legend}</div></div><div class="c"><h3>Time by work</h3>${totals.map(v=>`<div class="li"><span><i class="stat-dot" style="background:${v.color}"></i>${v.name}</span><b>${Math.round(v.minutes)} min</b></div>`).join('')}</div>`}
/* Care giving */
function r1(){const p=D.p;
return `${+p.kids>0?`<div class="c"><h3>📚 Homework helper</h3><div class="f"><input id="kn" placeholder="Child's name"><input id="kc" placeholder="Class"><input id="kb" placeholder="Board (CBSE/ICSE/State)"><input id="ks" placeholder="Subject"><input id="kh" placeholder="Chapter"><button onclick="add('kids',{n:V('kn'),c:V('kc'),b:V('kb'),s:V('ks'),h:V('kh')},'n')">Save child</button></div>${D.kids.map((k,i)=>{const q=`${k.b} class ${k.c} ${k.s} ${k.h}`;return `<div class="li"><span><b>${k.n}</b> · ${k.c} · ${k.s}: ${k.h}</span><span><a href="${yt(q+' explanation')}" target="_blank">▶ Learn</a> · <a href="${yt(q+' quiz')}" target="_blank">🧠 Quiz video</a> · <a href="${gg(q+' quiz online mcq')}" target="_blank">✏️ MCQ</a> <button class="x" onclick="del('kids',${i})">✕</button></span></div>`}).join('')}</div>`:''}
<div class="c"><h3>🩺 Appointments</h3><div class="row"><input id="apt" placeholder="Doctor / school / meeting"><input id="apd" type="datetime-local"><input id="apn" placeholder="Brief note"><button onclick="add('appts',{t:V('apt'),d:V('apd'),n:V('apn')},'d')">Add</button></div>${list('appts',a=>`<b>${a.t}</b> ${a.d.replace('T',' ')}<br><small>${a.n||''}</small>`)}<small>Appointments within 24 h pop up as sticky notes.</small></div>
${+p.kids>0?tutorCard():''}
${+p.old>0?`<div class="c"><h3>👵 Elder care</h3><p>Caring for ${p.old}. Add their medicines and check-ups under Appointments.</p></div>`:''}`}
function tutorCard(){D.tutorLog=D.tutorLog||[];const run=D.tutorRun,kids=D.kids||[],subject=run?run.subject:'',topic=run?run.topic:'',child=run?run.child:'';
return `<div class="c"><h3>📚 Child tutoring</h3><div class="f"><label for="tutorChild">Child</label><select id="tutorChild" onchange="updateTutorVideo()" ${run?'disabled':''}><option value="">Choose a child</option>${kids.map(k=>`<option value="${esc(k.n)}" ${child==k.n?'selected':''}>${esc(k.n)}</option>`).join('')}</select><label for="tutorSubject">Subject</label><input id="tutorSubject" list="tutorSubjects" placeholder="e.g. Maths, Science" value="${esc(subject)}" oninput="updateTutorVideo()" ${run?'disabled':''}><datalist id="tutorSubjects">${[...new Set(kids.map(k=>k.s).filter(Boolean))].map(s=>`<option value="${esc(s)}"></option>`).join('')}</datalist><label for="tutorTopic">Topic</label><input id="tutorTopic" placeholder="e.g. Fractions" value="${esc(topic)}" oninput="updateTutorVideo()" ${run?'disabled':''}><div class="row"><button onclick="startTutoring()" ${run?'disabled':''}>Start timer</button><a id="tutorVideoLink" href="${yt([child,subject,topic].filter(Boolean).join(' '))}">Search YouTube results</a></div></div>${run?`<p>Studying <b>${esc(run.subject)} · ${esc(run.topic)}</b> with ${esc(run.child)}</p><div class="big tutor-clock" id="tutorElapsed">${formatTutorTime((Date.now()-run.start)/1000)}</div><button class="x" onclick="stopTutoring()">Stop timer</button>`:''}<h4>Recent tutoring sessions</h4>${D.tutorLog.slice(0,8).map(s=>`<div class="li"><span><b>${esc(s.child)}</b> · ${esc(s.subject)}: ${esc(s.topic)}<br><small>${formatTutorTime(s.seconds)} studied</small></span><a href="${yt(`${s.subject} ${s.topic} ${s.child}`)}">YouTube</a></div>`).join('')||'<small>No tutoring sessions yet</small>'}</div>`}
function updateTutorVideo(){const link=$('#tutorVideoLink');if(!link)return;const query=[V('tutorChild'),V('tutorSubject'),V('tutorTopic')].filter(Boolean).join(' ');link.href=yt(query)}
function startTutoring(){const child=V('tutorChild').trim(),subject=V('tutorSubject').trim(),topic=V('tutorTopic').trim();if(!child||!subject||!topic){toast('Choose a child, subject and topic first');return}D.tutorRun={child,subject,topic,start:Date.now()};save();rr()}
function stopTutoring(){if(!D.tutorRun)return;D.tutorLog=D.tutorLog||[];D.tutorLog.unshift({...D.tutorRun,seconds:Math.max(0,Math.floor((Date.now()-D.tutorRun.start)/1000))});D.tutorRun=null;save();rr()}
const formatTutorTime=seconds=>{const elapsed=Math.max(0,Math.floor(seconds));return[String(Math.floor(elapsed/3600)).padStart(2,'0'),String(Math.floor(elapsed/60)%60).padStart(2,'0'),String(elapsed%60).padStart(2,'0')].join(':')};
setInterval(()=>{const counter=$('#tutorElapsed');if(counter&&D&&D.tutorRun)counter.textContent=formatTutorTime((Date.now()-D.tutorRun.start)/1000)},1000);
function saveWorkSettings(){D.workOut=V('wo')||D.p.out||'18:00';D.workLead=Number(V('wl'))||15;save();rr();toast('Work reminder saved')}
function r4(){const p=D.p,leave=D.workOut||p.out||'18:00',lead=Number(D.workLead)||15;
return `<div class="c"><h3>⏰ Departure & cab reminder</h3><p>Set your usual leaving time. We’ll remind you to book a cab in advance.</p><small>Keep this app open for the reminder to ring.</small><div class="f"><label for="wo">Leaving work</label><input id="wo" type="time" value="${leave}"><label for="wl">Remind me to book a cab</label><select id="wl"><option value="5" ${lead==5?'selected':''}>5 minutes before</option><option value="10" ${lead==10?'selected':''}>10 minutes before</option><option value="15" ${lead==15?'selected':''}>15 minutes before</option><option value="30" ${lead==30?'selected':''}>30 minutes before</option></select><button onclick="saveWorkSettings()">Save reminder</button></div><div class="row"><a href="https://m.uber.com/" target="_blank"><button>Book Uber</button></a><a href="https://www.olacabs.com/" target="_blank"><button class="g">Book Ola</button></a><a href="https://rapido.bike/" target="_blank"><button>Book Rapido</button></a></div></div>
<div class="c"><h3>🗂 Workspace</h3><div class="row"><input id="tk" placeholder="Task" style="flex:1"><select id="tp"><option>High</option><option>Medium</option><option>Low</option></select><button onclick="add('tasks',{t:V('tk'),p:V('tp'),x:0},'t')">Add</button></div>${D.tasks.map((t,i)=>`<div class="li"><span style="${t.x?'text-decoration:line-through;opacity:.5':''}"><input type="checkbox" ${t.x?'checked':''} onchange="D.tasks[${i}].x=this.checked?1:0;save();rr()"> ${t.t} <small>(${t.p})</small></span><button class="x" onclick="del('tasks',${i})">✕</button></div>`).join('')||'<small>No tasks yet</small>'}</div>`}
/* Self care */
const TH=[[/suicide|kill myself|end my life|hurt myself/,'I’m really glad you told me. Please reach out right now to someone you trust, or call Tele-MANAS at 14416 (India) or your local emergency number. You deserve support.'],[/sad|cry|low|depress/,'I’m sorry you feel this way. Your feelings are valid. Want to share what triggered it today?'],[/anx|worr|panic|stress/,'Let’s slow down: breathe in for 4, hold 4, out for 6, three times. What is the biggest worry right now?'],[/tired|exhaust|burn/,'You carry a lot. Rest is productive too. What is one thing you can hand off or skip today?'],[/angry|frustrat|irritat/,'Anger often signals an unmet need. What do you need most right now?'],[/lonely|alone/,'You’re not alone here. Is there a friend you could message for a small chat today?'],[/thank/,'Always here for you 💜']];
function r2(){return `<div class="c"><h3>🧘 Meditation timer</h3><div class="row"><input id="mm" type="number" value="20" min="1" style="width:80px"> min<button onclick="med()">Start</button><button class="x" onclick="clearInterval(mt);ms=0;rr()">Reset</button></div><div class="big" id="md">${ms?fm(ms):'--:--'}</div><a href="${yt('20 minute guided meditation')}" target="_blank"><button class="g">▶ Meditation video</button></a><small> Video link opens when the timer ends.</small></div>
<div class="c"><h3>💬 Feel-better chat</h3><div class="chat">${chatH(tb2)}</div><div class="row"><input id="ti" placeholder="How are you feeling?" style="flex:1" onkeydown="if(event.key=='Enter')ther()"><button onclick="ther()">Send</button></div><small>A supportive companion, not a replacement for a therapist.</small></div>
<div class="c"><h3>🎬 Movies & series</h3><div class="row"><input id="mv" placeholder="Title"><select id="mty"><option>Movie</option><option>Series</option></select><select id="mst"><option>Want to watch</option><option>Watching</option><option>Watched</option></select><button onclick="add('movies',{t:V('mv'),y:V('mty'),s:V('mst')},'t')">Add</button></div>${list('movies',m=>`${m.y=='Movie'?'🎬':'📺'} <b>${m.t}</b> · ${m.s}`)}<a href="${gg('new OTT movies web series releases this week India')}" target="_blank">🔔 See new releases this week</a></div>`}
const fm=s=>String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');
function med(){clearInterval(mt);ms=Math.max(1,+V('mm')||20)*60;mt=setInterval(()=>{ms--;const e=$('#md');if(e)e.textContent=fm(ms);if(ms<=0){clearInterval(mt);toast('🧘 Done! Open the meditation video.');window.open(yt('20 minute guided meditation'),'_blank')}},1000)}
function ther(){const q=V('ti').trim();if(!q)return;tb2.push([1,q]);const r=TH.find(x=>x[0].test(q.toLowerCase()));tb2.push([0,r?r[1]:'Thank you for sharing. Tell me more – how has this been affecting your day?']);rr()}
/* Emergency */
function sos(){const n=(D.p.ecp||'').replace(/\s/g,'');if(!n){alert('No emergency number saved');return}location.href='tel:'+n}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
function voice(){if(rec){stopV();return}if(!SR){alert('Voice recognition is not supported in this browser (try Chrome).');return}
try{rec=new SR();rec.continuous=true;rec.lang='en-IN';rec.onresult=e=>{const t=[...e.results].slice(-1)[0][0].transcript.toLowerCase();if(/help|emergency|bachao|save me/.test(t)){toast('🚨 Calling emergency contact…');setTimeout(sos,800)}};rec.onend=()=>{if(rec)try{rec.start()}catch(e){}};rec.start();$('#vb').textContent='🎙 Voice SOS: ON (tap to stop)'}catch(e){rec=null}}
function stopV(){if(rec){const r=rec;rec=null;try{r.stop()}catch(e){}}const b=$('#vb');if(b)b.textContent='🎙 Voice SOS: off'}
(function(){const l=ld('last');if(l)$('#em').value=l})();